"""paid_leaves_left added

Revision ID: 18107b971ac3
Revises: 2233e4bc80e8
Create Date: 2024-04-17 13:19:54.772431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18107b971ac3'
down_revision = '2233e4bc80e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_leaves_left', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.drop_column('paid_leaves_left')

    # ### end Alembic commands ###
