"""paid_leaves_left added

Revision ID: 2233e4bc80e8
Revises: 70f7f690ccab
Create Date: 2024-04-17 13:13:45.447921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2233e4bc80e8'
down_revision = '70f7f690ccab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.drop_column('paid_leaves_left')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_leaves_left', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
