"""New token time 10 mins.

Revision ID: 5adba364efca
Revises: 6a7bc5d1ad57
Create Date: 2024-04-19 17:50:36.095019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5adba364efca'
down_revision = '6a7bc5d1ad57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
