"""leave column name change

Revision ID: a8cb045ca8f7
Revises: 18107b971ac3
Create Date: 2024-04-17 14:46:18.650465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cb045ca8f7'
down_revision = '18107b971ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leaves', sa.Integer(), nullable=True))
        batch_op.drop_column('paid_leaves_left')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_leaves_left', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('leaves')

    # ### end Alembic commands ###
