"""Leave Table modified

Revision ID: b7135113da1f
Revises: a8cb045ca8f7
Create Date: 2024-04-17 19:20:30.710430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7135113da1f'
down_revision = 'a8cb045ca8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_managment', schema=None) as batch_op:
        batch_op.alter_column('leave_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_managment', schema=None) as batch_op:
        batch_op.alter_column('leave_status',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
