"""empty message

Revision ID: d3ec7f197768
Revises: 5adba364efca
Create Date: 2024-04-19 19:52:25.886345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3ec7f197768'
down_revision = '5adba364efca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_boarding', sa.Date(), nullable=True))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_created')

    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.drop_column('on_boarding')

    # ### end Alembic commands ###
